### PR TITLE
Allow trailing semicolon in SQL

### PR DESCRIPTION
**Pull request by git-hulk**

### CODE REVIEW

**Comment by makenowjust** [comment]
@git-hulk When I designed the parser, I considered semicolons should be proceeded with before parsing. Do you have any reason that they should be proceeded on parsing?

**Comment by git-hulk** [comment]
@makenowjust Thanks for your quick reply. We use `memefish` to format the Spanner SQL
and users may copy their SQL statements which ends with semicolons. Does it have any
side effect if we allow the trailing semicolon?

**Comment by makenowjust** [comment]
@git-hulk My position: Semicolon is just a separator of a statement, thus this is not a part of a statement. Your change may make it difficult that use semicolons in such a correct way.

You should use `ParseStatements` instead in this case.

**Comment by git-hulk** [comment]
@makenowjust Thanks for your kindly reply, let’s close this PR.

**Pull request closed without merging**
